import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Share2, Copy, Check, Twitter } from "lucide-react";
import { useCreateShareCard } from "@codetune/api-client-react";

interface ShareDialogProps {
  isOpen: boolean;
  onClose: () => void;
  soundtrackId: string;
  repoName: string;
  genre: string;
}

export function ShareDialog({ isOpen, onClose, soundtrackId, repoName, genre }: ShareDialogProps) {
  const [copied, setCopied] = useState(false);
  const { mutateAsync: createShareCard, isPending } = useCreateShareCard();
  const [shareData, setShareData] = useState<{ url: string; text: string } | null>(null);

  const handleShare = async () => {
    try {
      const result = await createShareCard({ data: { id: soundtrackId, repoName, genre } });
      setShareData({ url: result.shareUrl, text: result.shareText });
    } catch {
      setShareData({
        url: `${window.location.origin}/?soundtrack=${soundtrackId}`,
        text: `${repoName} has a soundtrack. Genre: ${genre} — generated by CodeTune.`,
      });
    }
  };

  const copy = () => {
    if (shareData) {
      navigator.clipboard.writeText(shareData.url);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <Dialog
      open={isOpen}
      onOpenChange={(open) => {
        if (!open) { onClose(); setShareData(null); }
        else handleShare();
      }}
    >
      <DialogContent className="sm:max-w-md border-border bg-background">
        <DialogHeader>
          <DialogTitle className="text-lg font-bold tracking-tight">Share your track</DialogTitle>
          <DialogDescription className="text-sm text-muted-foreground">
            Let the world hear the sound of your code.
          </DialogDescription>
        </DialogHeader>

        {isPending && !shareData ? (
          <div className="py-12 flex flex-col items-center gap-3">
            <div className="w-6 h-6 border-2 border-border border-t-foreground rounded-full animate-spin" />
            <p className="text-xs text-muted-foreground">Generating share card…</p>
          </div>
        ) : shareData ? (
          <div className="space-y-5 pt-2">
            {/* Share card preview */}
            <div className="aspect-video rounded-xl border border-border bg-card flex flex-col items-center justify-center p-8 text-center">
              <p className="text-xs text-muted-foreground uppercase tracking-widest mb-3">{genre} soundtrack</p>
              <h3 className="text-2xl font-bold tracking-tight mb-1">{repoName}</h3>
              <p className="text-sm text-muted-foreground">This repo has a soundtrack.</p>
              <p className="text-xs text-muted-foreground/40 mt-4 tracking-widest">CODETUNE</p>
            </div>

            {/* URL copy */}
            <div className="flex gap-2">
              <div className="flex-1 bg-input border border-border rounded-lg px-3 py-2.5 text-xs font-mono text-muted-foreground truncate">
                {shareData.url}
              </div>
              <button
                onClick={copy}
                className="px-3 rounded-lg border border-border hover:bg-accent transition-colors flex items-center justify-center"
              >
                {copied ? <Check className="w-4 h-4 text-foreground" /> : <Copy className="w-4 h-4 text-muted-foreground" />}
              </button>
            </div>

            {/* Share buttons */}
            <div className="grid grid-cols-2 gap-2">
              <a
                href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(shareData.text)}`}
                target="_blank"
                rel="noreferrer"
                className="flex items-center justify-center gap-2 py-2.5 rounded-xl border border-border text-xs font-medium hover:bg-accent transition-colors"
              >
                <Twitter className="w-4 h-4" /> Post on X
              </a>
              <button
                onClick={copy}
                className="flex items-center justify-center gap-2 py-2.5 rounded-xl bg-foreground text-background text-xs font-medium hover:opacity-90 transition-opacity"
              >
                <Share2 className="w-4 h-4" /> Copy link
              </button>
            </div>
          </div>
        ) : null}
      </DialogContent>
    </Dialog>
  );
}
