import { useRef, useState } from "react";
import { Download, Share2, Check } from "lucide-react";
import { motion } from "framer-motion";
import type { MusicParamsData, CodeMetricsData } from "./CodeDNA";

interface SoundtrackCardProps {
  repoName: string;
  genre: string;
  mode: string;
  musicParams: MusicParamsData;
  codeMetrics: CodeMetricsData;
}

function MiniWaveform({ bars = 28 }: { bars?: number }) {
  const heights = Array.from({ length: bars }, (_, i) => {
    const seed = Math.sin(i * 2.3 + 1.7) * 0.5 + 0.5;
    const envelope = Math.sin((i / bars) * Math.PI);
    return 15 + Math.round(seed * envelope * 40);
  });

  return (
    <div className="flex items-end gap-0.5" style={{ height: 48 }}>
      {heights.map((h, i) => (
        <div
          key={i}
          className="flex-1 rounded-sm bg-white/30"
          style={{ height: h }}
        />
      ))}
    </div>
  );
}

export function SoundtrackCard({
  repoName,
  genre,
  mode,
  musicParams,
  codeMetrics,
}: SoundtrackCardProps) {
  const cardRef = useRef<HTMLDivElement>(null);
  const [downloading, setDownloading] = useState(false);
  const [sharing, setSharing] = useState(false);
  const [shareDone, setShareDone] = useState(false);
  const [actionFeedback, setActionFeedback] = useState<string | null>(null);

  const starLabel =
    codeMetrics.stars >= 50000 ? `${(codeMetrics.stars / 1000).toFixed(0)}k stars` :
    codeMetrics.stars >= 1000  ? `${(codeMetrics.stars / 1000).toFixed(1)}k stars` :
                                 `${codeMetrics.stars} stars`;

  const fileBaseName = `${repoName.replace(/\//g, "-")}-codetune`;
  const shareText = `${repoName} as ${genre} music - ${musicParams.bpm} BPM, ${musicParams.scale}, ${musicParams.mood}. Generated by CodeTune.`;

  function showFeedback(message: string, timeoutMs = 2400) {
    setActionFeedback(message);
    window.setTimeout(() => setActionFeedback(null), timeoutMs);
  }

  async function renderCardBlob(): Promise<Blob> {
    if (!cardRef.current) {
      throw new Error("Card preview is not available.");
    }

    if ("fonts" in document) {
      await document.fonts.ready;
    }

    await new Promise((resolve) => window.setTimeout(resolve, 80));
    const { toBlob } = await import("html-to-image");
    const blob = await toBlob(cardRef.current, {
      cacheBust: true,
      backgroundColor: "#0a0a0a",
      pixelRatio: Math.min(window.devicePixelRatio * 2, 4),
    });

    if (!blob) {
      throw new Error("Failed to render soundtrack card.");
    }

    return blob;
  }

  async function handleDownload() {
    setDownloading(true);
    setActionFeedback(null);
    try {
      const blob = await renderCardBlob();
      const objectUrl = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.download = `${fileBaseName}.png`;
      link.href = objectUrl;
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.setTimeout(() => URL.revokeObjectURL(objectUrl), 1000);
      showFeedback("Card downloaded.");
    } catch (error) {
      console.error("Soundtrack card download failed", error);
      showFeedback("Card export failed. Try again.", 2800);
    } finally {
      setDownloading(false);
    }
  }

  async function handleShareCard() {
    setSharing(true);
    setShareDone(false);
    setActionFeedback(null);
    try {
      const blob = await renderCardBlob();
      const file = new File([blob], `${fileBaseName}.png`, { type: "image/png" });

      if (
        typeof navigator.share === "function" &&
        (!navigator.canShare || navigator.canShare({ files: [file] }))
      ) {
        await navigator.share({
          title: `${repoName} soundtrack card`,
          text: shareText,
          files: [file],
        });
        setShareDone(true);
        showFeedback("Card shared.");
        return;
      }

      if (typeof ClipboardItem !== "undefined" && navigator.clipboard?.write) {
        await navigator.clipboard.write([
          new ClipboardItem({
            "image/png": blob,
          }),
        ]);
        setShareDone(true);
        showFeedback("Card image copied.");
        return;
      }

      await navigator.clipboard.writeText(shareText);
      setShareDone(true);
      showFeedback("Card details copied.");
    } catch (error) {
      console.error("Soundtrack card share failed", error);
      showFeedback("Card share failed. Try again.", 2800);
    } finally {
      setSharing(false);
      window.setTimeout(() => setShareDone(false), 1800);
    }
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.15, duration: 0.4 }}
      className="panel p-6"
    >
      <div className="flex items-center gap-2 mb-4">
        <div className="w-1.5 h-4 bg-foreground rounded-full" />
        <h3 className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">
          Soundtrack Card
        </h3>
      </div>

      <div
        ref={cardRef}
        className="relative rounded-2xl overflow-hidden select-none"
        style={{ background: "#0a0a0a", border: "1px solid rgba(255,255,255,0.08)" }}
      >
        <div
          className="absolute inset-0 pointer-events-none"
          style={{
            backgroundImage: `radial-gradient(circle at 20% 80%, rgba(255,255,255,0.03) 0%, transparent 60%),
                             radial-gradient(circle at 80% 20%, rgba(255,255,255,0.03) 0%, transparent 60%)`,
          }}
        />

        <div className="relative p-6 flex flex-col gap-5">
          <div className="flex items-start justify-between">
            <div>
              <div className="flex items-center gap-2 mb-1.5">
                <div className="w-5 h-5 rounded-md bg-white flex items-center justify-center">
                  <svg className="w-3 h-3" viewBox="0 0 24 24" fill="black">
                    <path d="M12 3v10.55c-.59-.34-1.27-.55-2-.55-2.21 0-4 1.79-4 4s1.79 4 4 4 4-1.79 4-4V7h4V3h-6z" />
                  </svg>
                </div>
                <span className="text-xs font-semibold text-white/60 tracking-widest uppercase">CodeTune</span>
              </div>
              <p className="text-white/40 text-xs font-medium mb-0.5">github.com/</p>
              <h2 className="text-xl font-bold text-white leading-tight">
                {repoName.includes("/") ? repoName.split("/")[1] : repoName}
              </h2>
              {repoName.includes("/") && (
                <p className="text-white/40 text-xs mt-0.5">{repoName.split("/")[0]}</p>
              )}
            </div>

            <div className="flex flex-col items-end gap-1.5">
              <span className="text-xs font-bold uppercase tracking-widest px-2.5 py-1 rounded-full bg-white text-black">
                {genre}
              </span>
              <span className="text-[10px] text-white/40 uppercase tracking-wider">{mode}</span>
            </div>
          </div>

          <MiniWaveform bars={30} />

          <div className="grid grid-cols-3 gap-3">
            {[
              { label: "BPM", value: String(musicParams.bpm) },
              { label: "Key", value: musicParams.scale.split(" ").slice(0, 2).join(" ") },
              { label: "Mood", value: musicParams.mood.split(",")[0].trim() },
              { label: "Language", value: codeMetrics.primaryLanguage || "-" },
              { label: "Stars", value: starLabel },
              { label: "Lines", value: codeMetrics.totalLines >= 1000 ? `${(codeMetrics.totalLines / 1000).toFixed(1)}k` : String(codeMetrics.totalLines) },
            ].map((stat) => (
              <div key={stat.label} className="rounded-xl px-3 py-2.5" style={{ background: "rgba(255,255,255,0.05)" }}>
                <p className="text-[9px] font-semibold text-white/40 uppercase tracking-wider mb-0.5">{stat.label}</p>
                <p className="text-sm font-bold text-white truncate">{stat.value}</p>
              </div>
            ))}
          </div>

          <div className="flex items-center justify-between pt-1 border-t" style={{ borderColor: "rgba(255,255,255,0.06)" }}>
            <p className="text-[10px] text-white/30">Every function, loop, and pattern becomes music.</p>
            <p className="text-[10px] text-white/20">codetune.app</p>
          </div>
        </div>
      </div>

      <div className="flex gap-2 mt-4">
        <motion.button
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.97 }}
          onClick={handleDownload}
          disabled={downloading}
          className="flex-1 flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl bg-foreground text-background text-xs font-semibold transition-all disabled:opacity-50"
        >
          <Download className="w-3.5 h-3.5" />
          {downloading ? "Exporting..." : "Download Card"}
        </motion.button>
        <motion.button
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.97 }}
          onClick={handleShareCard}
          disabled={sharing}
          className="flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl border border-border text-xs font-semibold transition-all hover:bg-accent disabled:opacity-50"
        >
          {shareDone ? <Check className="w-3.5 h-3.5" /> : <Share2 className="w-3.5 h-3.5" />}
          {sharing ? "Sharing..." : shareDone ? "Shared" : "Share Card"}
        </motion.button>
      </div>

      {actionFeedback && (
        <p className="mt-2 text-xs text-muted-foreground">{actionFeedback}</p>
      )}
    </motion.div>
  );
}
